# LIBXLFPARSER_FOUND - true if library and headers were found
# LIBXLFPARSER_INCLUDE_DIRS - include directories
# LIBXLFPARSER_LIBRARIES - library directories

find_package(PkgConfig)
pkg_check_modules(PC_LIBXLFPARSER QUIET libxlfparser)

if(DEFINED ENV{LIBXLFPARSER_DIR})
    set(MY_LIBXLFPARSER_INCLUDEDIR $ENV{LIBXLFPARSER_DIR}/include)
    set(MY_LIBXLFPARSER_LIBRARYDIR $ENV{LIBXLFPARSER_DIR}/lib)
else()
    set(MY_LIBXLFPARSER_INCLUDEDIR "")
    set(MY_LIBXLFPARSER_LIBRARYDIR "")
endif()

find_path(LIBXLFPARSER_INCLUDE_DIR xlfparser/xlfparser.h
	HINTS ${MY_LIBXLFPARSER_INCLUDEDIR} ${PC_LIBXLFPARSER_INCLUDEDIR} ${PC_LIBXLFPARSER_INCLUDE_DIRS})

find_library(LIBXLFPARSER_LIBRARY NAMES xlfparser libxlfparser
	HINTS ${MY_LIBXLFPARSER_LIBRARYDIR} ${PC_LIBXLFPARSER_LIBDIR} ${PC_LIBXLFPARSER_LIBRARY_DIRS})

set(LIBXLFPARSER_LIBRARIES ${LIBXLFPARSER_LIBRARY})
set(LIBXLFPARSER_INCLUDE_DIRS ${LIBXLFPARSER_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LIBXLFPARSER DEFAULT_MSG LIBXLFPARSER_LIBRARY LIBXLFPARSER_INCLUDE_DIR)

mark_as_advanced(LIBXLFPARSER_INCLUDE_DIR LIBXLFPARSER_LIBRARY)
